-- EXCLUSAO
DECLARE @name varchar(256), @campo varchar(10)
DECLARE TABELA SCROLL CURSOR FOR 
SELECT name FROM sysobjects WHERE xtype = 'U' AND SUBSTRING(name,4,10) = '920'

OPEN TABELA
FETCH FIRST FROM TABELA INTO @name
WHILE @@FETCH_STATUS = 0
	BEGIN
	PRINT 'Excluindo tabela ' + @name + '...'
	EXEC('DROP TABLE ' + @name)
	
	FETCH NEXT FROM TABELA INTO @name
END
CLOSE TABELA
DEALLOCATE TABELA
